### ISSUE TITLE
No Proper Documentation

### ISSUE THREAD

**Issue by naszifnaaz** [Saif-sk5417/NatureTrug.com#36]
Add proper documentation of your app in Readme including screenshots, functionaliteas and tech stack used in the app

**Comment by vaishu0428** [comment]
Documentation Completed by vaishu0428

**Comment by naszifnaaz** [comment]
You don't have to assign issues to me, close the issues yourself and at the end of the day raise a PR and assign me as a reviewer, will aprove the PR and you can merge it after. @vaishu0428
